const express = require('express');
const authController = require('../controllers/authController');
const almsController = require('../controllers/almsController');
const almsRouter = express.Router();
const almsRouterProtected = express.Router();
almsRouterProtected.use(authController.verifyAdmin);
almsRouterProtected.route('/add').post(almsController.addAlms);
almsRouterProtected.route('/edit').post(almsController.editAlms);
almsRouterProtected.route('/delete').post(almsController.deleteAlms);
almsRouter.route('/all').get(almsController.getAllAlms);
module.exports = {almsRouter, almsRouterProtected};
