const express = require('express');
const authController = require('../controllers/authController');
const eventController = require('../controllers/eventController');
const eventRouterProtected = express.Router();
const eventRouter = express.Router();
eventRouterProtected.use(authController.verifyAdmin);
eventRouterProtected.route('/add').post(eventController.addEvent);
eventRouterProtected.route('/edit').post(eventController.editEvent);
eventRouterProtected.route('/delete').post(eventController.deleteEvent);
eventRouter.route('/all').get(eventController.getAllEvents);
module.exports = {eventRouter, eventRouterProtected};
